### ISSUE TITLE
Error on dev startup

### ISSUE THREAD

**Issue by kariso2000** [AIforGoodSimulator/model-server#164]
I'm seeing the following error on the dev instance seems related to filesystem not finding a path.

```python
2020-11-20T14:01:03.215751940Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
2020-11-20T14:01:03.215756540Z     raise value
2020-11-20T14:01:03.215760941Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
2020-11-20T14:01:03.215765441Z     rv = self.dispatch_request()
2020-11-20T14:01:03.215769841Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
2020-11-20T14:01:03.215789041Z     return self.view_functions[rule.endpoint](**req.view_args)
2020-11-20T14:01:03.215811541Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/dash/dash.py", line 1076, in dispatch
2020-11-20T14:01:03.215816141Z     response.set_data(func(*args, outputs_list=outputs_list))
2020-11-20T14:01:03.215820841Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/dash/dash.py", line 1007, in add_context
2020-11-20T14:01:03.215825441Z     output_value = func(*args, **kwargs)  # %% callback invoked %%
2020-11-20T14:01:03.215829941Z   File "/home/site/wwwroot/ai4good/webapp/waiting_page.py", line 88, in check_model_status
2020-11-20T14:01:03.215834641Z     mr = model_runner.get_result(model, profile, camp)
2020-11-20T14:01:03.215839141Z   File "/home/site/wwwroot/ai4good/webapp/model_runner.py", line 236, in get_result
2020-11-20T14:01:03.215843841Z     return self.facade.rs.load(_mdl.id(), res_id)
2020-11-20T14:01:03.215848241Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/typeguard/__init__.py", line 822, in wrapper
2020-11-20T14:01:03.215852941Z     retval = func(*args, **kwargs)
2020-11-20T14:01:03.215857541Z   File "/home/site/wwwroot/ai4good/models/model_result_store.py", line 48, in load
2020-11-20T14:01:03.215862241Z     with open(p, 'rb') as handle:
2020-11-20T14:01:03.215866941Z FileNotFoundError: [Errno 2] No such file or directory: '/home/site/wwwroot/ai4good/utils/../../fs/model_results/compartmental-model_c4e284a3eef5739118b47524a35891
5491cc7ba7.pkl'
2020-11-20T14:01:03.215667740Z 2020-11-20 14:01:03,181 - ai4good.webapp.apps - ERROR - Exception on /sim/_dash-update-component [POST]
2020-11-20T14:01:03.215880741Z Traceback (most recent call last):
2020-11-20T14:01:03.215885341Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
2020-11-20T14:01:03.215890042Z     response = self.full_dispatch_request()
2020-11-20T14:01:03.215899542Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
2020-11-20T14:01:03.215904142Z     rv = self.handle_user_exception(e)
2020-11-20T14:01:03.215908742Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
2020-11-20T14:01:03.215917742Z     reraise(exc_type, exc_value, tb)
2020-11-20T14:01:03.215922442Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
2020-11-20T14:01:03.215927042Z     raise value
2020-11-20T14:01:03.215931742Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
2020-11-20T14:01:03.215936442Z     rv = self.dispatch_request()
2020-11-20T14:01:03.215940942Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
2020-11-20T14:01:03.215945742Z     return self.view_functions[rule.endpoint](**req.view_args)
2020-11-20T14:01:03.215950342Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/dash/dash.py", line 1076, in dispatch
2020-11-20T14:01:03.215954942Z     response.set_data(func(*args, outputs_list=outputs_list))
2020-11-20T14:01:03.215959542Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/dash/dash.py", line 1007, in add_context
2020-11-20T14:01:03.215964142Z     output_value = func(*args, **kwargs)  # %% callback invoked %%
2020-11-20T14:01:03.215968642Z   File "/home/site/wwwroot/ai4good/webapp/waiting_page.py", line 88, in check_model_status
2020-11-20T14:01:03.215973342Z     mr = model_runner.get_result(model, profile, camp)
2020-11-20T14:01:03.215977842Z   File "/home/site/wwwroot/ai4good/webapp/model_runner.py", line 236, in get_result
2020-11-20T14:01:03.215982442Z     return self.facade.rs.load(_mdl.id(), res_id)
2020-11-20T14:01:03.215987042Z   File "/opt/python/3.7.9/lib/python3.7/site-packages/typeguard/__init__.py", line 822, in wrapper
2020-11-20T14:01:03.215991642Z     retval = func(*args, **kwargs)
2020-11-20T14:01:03.215996142Z   File "/home/site/wwwroot/ai4good/models/model_result_store.py", line 48, in load
2020-11-20T14:01:03.216000742Z     with open(p, 'rb') as handle:
2020-11-20T14:01:03.216005242Z FileNotFoundError: [Errno 2] No such file or directory: '/home/site/wwwroot/ai4good/utils/../../fs/model_results/compartmental-model_c4e284a3eef5739118b47524a35891
5491cc7ba7.pkl'
```

**Comment by pardf** [comment]
@billlyzhaoyh commented that it may relate tohow results from multiple model outputs are collated to form the final output.
